### ISSUE TITLE
[CLIENT] 

### ISSUE THREAD

**Issue by suhyun22** [Medici-Mansion/dreamer#52]
### 수정 요청

**Artistic Reference**
1) Makoto Shinkai 이미지 변경: figma 확인 부탁
2) "Makoto Shinkai"와 "Studio Ghibli" 위치 변경

<img width="740" alt="스크린샷 2024-02-14 오후 10 01 11" src="https://github.com/Medici-Mansion/dreamer/assets/112176958/8c10d8a2-71e2-45bc-9677-feabde76bcec">

**Comment by raymondanythings** [comment]
@LeeBonHoon1 
감사합니다

**Comment by raymondanythings** [comment]
머지로 인한 클로즈
